### ISSUE TITLE
hermitkrab cli

### ISSUE THREAD

**Issue by Hoxmot** [Hoxmot/hermitkrab#2]
Once core functionality (#1) exposes API, I should implement a CLI tool to find the apartment.

It will take a config from a file or from values provided as flags. Then, it'll query for apartments and open the browser once it finds the places.

- [ ] Implement monorepo
- [ ] Simple search command
- [ ] Create config interactively via CLI
- [ ] Pass config through flags
- [ ] Publish the package
